
path: '/content/gdrive/My Drive/train/data' # dataset root dir
train: images/train  # train images (relative to 'path')
val: images/train  # val images (relative to 'path')

# Classes
names:
  0: alpaca
